// Single source of truth mapping the icon-name strings used in
// servicesData.js to their lucide-react components. Every new component
// that needs to resolve a data-driven icon name imports getIcon from here
// instead of declaring its own local lookup object.
import {
  Award,
  BadgeCheck,
  BookOpenCheck,
  Briefcase,
  Building2,
  CalendarCheck2,
  ClipboardCheck,
  Clock,
  Coins,
  Cpu,
  Factory,
  FileBarChart,
  FileCheck2,
  FileSignature,
  FileSpreadsheet,
  GraduationCap,
  Gavel,
  Globe2,
  Handshake,
  HardHat,
  HeartHandshake,
  IdCard,
  Landmark,
  Lock,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Rocket,
  Scale,
  ScrollText,
  Search,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Stamp,
  Stethoscope,
  Store,
  TrendingUp,
  Users,
  UtensilsCrossed,
  Wrench,
  Zap,
} from "lucide-react";

const registry = {
  Award,
  BadgeCheck,
  BookOpenCheck,
  Briefcase,
  Building2,
  CalendarCheck2,
  ClipboardCheck,
  Clock,
  Coins,
  Cpu,
  Factory,
  FileBarChart,
  FileCheck2,
  FileSignature,
  FileSpreadsheet,
  GraduationCap,
  Gavel,
  Globe2,
  Handshake,
  HardHat,
  HeartHandshake,
  IdCard,
  Landmark,
  Lock,
  PiggyBank,
  Plane,
  Receipt,
  Repeat,
  Rocket,
  Scale,
  ScrollText,
  Search,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  Stamp,
  Stethoscope,
  Store,
  TrendingUp,
  Users,
  UtensilsCrossed,
  Wrench,
  Zap,
};

export function getIcon(name) {
  return registry[name] ?? Award;
}
